export const CREATE_ELECTION = "CREATE_ELECTION";
export const ENABLE_VOTING = "ENABLE_VOTING";
export const DISABLE_VOTING = "DISABLE_VOTING";
export const COMPILE_RESULT = "COMPILE_RESULT";
export const SHOW_RESULT = "SHOW_RESULT";
export const DECLARE_INTEREST = "DECLARE_INTEREST";
export const VOTE = "VOTE";